CREATE TABLE User (
	uid INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(32) NOT NULL UNIQUE,
	name VARCHAR(32),
	password CHAR(60),
	role TINYINT UNSIGNED
);

CREATE TABLE Thread (
	uid INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(32)
);

CREATE TABLE Message (
	uid BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	thread INT UNSIGNED NOT NULL,
	owner INT UNSIGNED NOT NULL,
	content VARCHAR(128) NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (thread) REFERENCES Thread(uid) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (owner) REFERENCES User(uid) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ThreadViewer (
	thread INT UNSIGNED NOT NULL,
	user INT UNSIGNED NOT NULL,
	FOREIGN KEY (thread) REFERENCES Thread(uid) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (user) REFERENCES User(uid) ON DELETE CASCADE ON UPDATE CASCADE
);
